sudo: false

language: go

go:
- 1.10.x

services:
- mysql

before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS rest_api_example;'

install:
- go get github.com/gorilla/mux
- go get github.com/go-sql-driver/mysql
- go get -u golang.org/x/lint/golint

email: false

script:
- go test -v -race ./...
- golint -set_exit_status
